modLoader="javafml" #mandatory
loaderVersion="${forge_loader_version_range}" #mandatory
license="${license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
displayName="${mod_name}" #mandatory

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional

authors="${mod_author}" #optional
credits="${credits}" #optional

description='''${description}'''

[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="midnightlib"
    mandatory=true
    embedded=true
    versionRange="1.4.1"
    ordering="NONE"
    side="BOTH"

[mc-publish]
    loaders = ['forge', 'neoforge']