name: build
env:
  MOD_NAME: Metabolism
on: workflow_call

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build

      - name: Upload Jars
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.MOD_NAME }}
          if-no-files-found: error
          path: |
            fabric/build/libs
            forge/build/libs
            common/build/libs